### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by Tofi-Dev** [arookas/DOOMWADCorrupter#1]
Where's the download?
Or How Do i Compile this?

( i meant download for a exe file )

**Comment by arookas** [comment]
@XxKoxsGamerxX I've now added a precompiled release [here](https://github.com/arookas/DOOMWADCorrupter/releases/tag/v0.1.12). To otherwise compile this, you'd have to gather the source files in the repository into a C# project, compile it, and link it with my [utility library](https://github.com/arookas/arookas).

**Comment by Tofi-Dev** [comment]
thank you

**Comment by Tofi-Dev** [comment]
Case Closed
